---
apiVersion: v1
kind: Namespace
metadata:
  name: newns
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  namespace: newns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
        - name: webserver
          image: ghcr.io/c1t1d0s7/go-myweb:alpine
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: newns
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: webservice
