apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-rs-dynamic
spec:
  replicas: 2
  selector:
    matchLabels:
      vol: nfs-dynamic
  template:
    metadata:
      labels:
        vol: nfs-dynamic
    spec:
      containers:
        - name: web-server
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-share
              mountPath: /usr/share/nginx/html
      volumes:
        - name: web-share
          persistentVolumeClaim:
            claimName: myapp-pvc-dynamic
