apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  annotations:
    kubernetes.io/change-cause: This version is v2
  labels:
    app: myapp-deploy
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 20
  replicas: 3
  selector:
    matchLabels:
      app: myapp-deploy
  template:
    metadata:
      labels:
        app: myapp-deploy
    spec:
      containers:
      - image: ghcr.io/c1t1d0s7/go-myweb:v2.0
        name: myapp
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-svc
spec:
  type: LoadBalancer
  selector:
    app: myapp-deploy
  ports:
    - port: 80
      targetPort: 8080
